In [1]:
import pandas as pd
import sqlite3
import datetime

# Test db

In [3]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [6]:
onehousing_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6836 entries, 0 to 6835
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   property_id           6833 non-null   object
 1   property_url          6836 non-null   object
 2   listing_title         6834 non-null   object
 3   total_price           6832 non-null   object
 4   unit_price            6832 non-null   object
 5   city                  6803 non-null   object
 6   district              6803 non-null   object
 7   alley_width           4785 non-null   object
 8   features              6834 non-null   object
 9   latitude              6834 non-null   float64
 10  longitude             6834 non-null   float64
 11  property_description  4896 non-null   object
 12  image_url             6834 non-null   object
dtypes: float64(2), object(11)
memory usage: 694.4+ KB

In [11]:
dup_id = onehousing_raw[onehousing_raw.duplicated()]['property_id'].unique().tolist()
len(dup_id)

786

In [26]:
onehousing_raw[(onehousing_raw['alley_width'].str.contains('\r\n')) & (onehousing_raw['alley_width'].notna())]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
0,ULHEKO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Lua-100m--P--Van-Phuc--Q--Ha-Dong--TP--Ha-Noi.ULHEKO,"Nhà mặt ngõ cách Phố Lụa 100m, P. Vạn Phúc, Q. Hà Đông, TP. Hà Nội",9.2 tỷ,271 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Bắc - 7.8m; Số tầng: 5; Diện tích: 33.9 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/355c72a5-37b5-4b62-819a-f1f34e64d071/2c9427839a4a2959019b2c413fa75633_CLONE/LIVING_ROOM/scaled_1000040570_1765975397648.jpg
1,SKUOOI,https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI,"Nhà mặt ngõ cách Xuân Đỉnh 50m, P. Xuân Đỉnh, Q. Bắc Từ Liêm, TP. Hà Nội",17 tỷ,422 triệu/m²,TP. Hà Nội,Q. Bắc Từ Liêm,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 4.1m; Số tầng: 6; Diện tích: 40.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/eb81035f-a264-4aed-932c-e524bac4e5e5/2c9427839a4a2959019ba140fe0c7de0_CLONE/LIVING_ROOM/image_picker_0225B86C-1140-496C-9131-6DC827356E26-75883-00001587015572D0_1767937910623.jpg
2,YWGUVT,https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Nguu-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.YWGUVT,"Nhà mặt ngõ cách Kim Ngưu 100m, P. Vĩnh Tuy, Q. Hai Bà Trưng, TP. Hà Nội",5.2 tỷ,203 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông Bắc - 1.2m; Số tầng: 4.5; Diện tích: 25.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/62ea34f7-62ce-4f11-92c8-cd8d8c9ca823/2c9427839a4a2959019b30c1bfac58c6_CLONE/LIVING_ROOM/scaled_1000060304_1766050118802.jpg
3,IIWMDZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ha-Tri-20m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.IIWMDZ,"Nhà mặt ngõ cách Hà Trì 20m, P. Hà Cầu, Q. Hà Đông, TP. Hà Nội",18.5 tỷ,242 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n6m - 7m,Hướng mặt tiền: Đông Nam - 5m; Số tầng: 4; Diện tích: 76.5 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8ebf97a2-39ac-491a-a797-aad2e820c127/2c9427839a4a2959019b48e5eb8d5f0c_CLONE/LIVING_ROOM/scaled_1000060911_1766455083168.jpg
4,NKHHRZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ,"Nhà mặt ngõ cách Thái Thịnh 30m, P. Thịnh Quang, Q. Đống Đa, TP. Hà Nội",19.5 tỷ,548 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\r\n3m - 4m,Hướng mặt tiền: Tây Bắc - 3.4m; Số tầng: 6; Diện tích: 35.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8995d755-c3d8-4b33-9b79-39c28c273d4f/2c9427839a4a2959019ba138a6847ddd_CLONE/LIVING_ROOM/image_picker_2E3A0736-3D43-4694-BD18-B10DAE346EF8-88338-00002DF9C82EA189_1767937353914.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,3ZDU0Y,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-Tung-Mau-200m--P--Cau-Dien--Q--Nam-Tu-Liem--TP--Ha-Noi.3ZDU0Y,"Nhà mặt ngõ cách Hồ Tùng Mậu 200m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội",8.1 tỷ,297 triệu/m²,TP. Hà Nội,Q. Nam Từ Liêm,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông - 3.9m; Số tầng: 5; Diện tích: 27.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/392d4278-2b7f-4422-868e-460288d0cc01/2c9427839a4a2959019b468985485ecf_CLONE/LIVING_ROOM/image_picker_1F0F8637-7D87-4131-AA22-CB9A4AAEEFF8-34865-000032F5B703AE4E_1766415874117.jpg
865,ANGLOU,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-De-20m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.ANGLOU,"Nhà mặt ngõ cách Bồ Đề 20m, P. Bồ Đề, Q. Long Biên, TP. Hà Nội",17.5 tỷ,328 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 3.7m; Số tầng: 7; Diện tích: 53.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/5dd47b58-65a3-41b4-ae70-bb30af8336f0/2c9427839a4a2959019b5e0f1fa269f4_CLONE/LIVING_ROOM/image_picker_2274BDFD-6944-4A03-A625-7CB0DF90408D-3465-0000025567CBBDFF_1767354176901.jpg
866,ECZA1C,https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Ha-Huy-Tap-300m--TT--Yen-Vien--H--Gia-Lam--TP--Ha-Noi.ECZA1C,"Nhà mặt ngõ cách Đường Hà Huy Tập 300m, TT. Yên Viên, H. Gia Lâm, TP. Hà Nội",3.65 tỷ,85 triệu/m²,TP. Hà Nội,H. Gia Lâm,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Tây Nam - 1.5m; Số tầng: 2; Diện tích: 43 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a4ef60e3-0b6e-4438-b5dd-96730277e20e/2c9427839a4a2959019b450a6ca25dad_CLONE/LOCAL_STREET/scaled_2081_1766390273009.jpg
867,URT8I8,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--200m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.URT8I8,"Nhà mặt ngõ cách Ngọc Thụy (mặt đê và đường gom chân đê) 200m, P. Ngọc Thụy, Q. Long Biên, TP. Hà Nội",8.6 tỷ,246 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Tây Nam - 3.7m; Số tầng: 5; Diện tích: 35 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/c578cf8f-09da-49a6-b3c9-ab5932b21dfa/2c94211a9a4a2a77019b460daaab6121_CLONE/LOCAL_STREET/scaled_IMG20251222164655_1766407188487.jpg
868,OCQGNV,https://onehousing.vn/bds/Nha-mat-pho-Dam-Quang-Trung--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.OCQGNV,"Nhà mặt phố Đàm Quang Trung, P. Long Biên, Q. Long Biên, TP. Hà Nội",12.9 tỷ,120 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n10m - 20m,Hướng mặt tiền: Bắc - 5m; Số tầng: 18; Số tầng hầm: 1; Diện tích: 107.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a4268e28-1629-41b0-b4da-8b7c170dd41f/2c94211a9a4a2a77019b2b6af93556bc_CLONE/LIVING_ROOM/scaled_1000073412_1766139321801.jpg

In [24]:
onehousing_raw[onehousing_raw['listing_title'].isna()]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
4432,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None

In [23]:
pd.set_option('display.max_colwidth', None)
yo = onehousing_raw[onehousing_raw['property_id'] == dup_id[0]]
yo['listing_title'].tolist()

['Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội']

## Test db mới tạo

In [3]:
with sqlite3.connect('output/real_estate_test.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [8]:
cleaned.duplicated().sum()

np.int64(0)

## Check onehousing_raw

In [34]:
dup_idx = onehousing_raw[onehousing_raw.duplicated()].index.tolist()

In [35]:
pd.set_option('display.max_colwidth', None)
# onehousing_raw[onehousing_raw['property_id'] == dup_id[2]][['property_id', 'property_description', 'listing_title', 'total_price', 'unit_price', 'city', 'district', 'features']]
none_des = []
have_des = []

for id in dup_idx:
    if pd.isna(onehousing_raw.iloc[id]['property_description']):
        none_des.append(onehousing_raw.loc[id, 'property_id'])
    else:
        have_des.append(id)

## Check cleaned

In [33]:
cleaned[cleaned['Yếu tố khác'] == ' ']

Empty DataFrame
Columns: [Tỉnh/Thành phố, Thành phố/Quận/Huyện/Thị xã, Xã/Phường/Thị trấn, Đường phố, Chi tiết, Nguồn thông tin, Tình trạng giao dịch, Thời điểm giao dịch/rao bán, Thông tin liên hệ, Giá rao bán/giao dịch, Giá ước tính, Loại đơn giá (đ/m2 hoặc đ/m ngang), Đơn giá đất, Lợi thế kinh doanh, Số tầng công trình, Tổng diện tích sàn, Đơn giá xây dựng, Năm xây dựng, Chất lượng còn lại, Diện tích đất (m2), Kích thước mặt tiền (m), Kích thước chiều dài (m), Số mặt tiền tiếp giáp, Hình dạng, Độ rộng ngõ/ngách nhỏ nhất (m), Khoảng cách tới trục đường chính (m), Mục đích sử dụng đất, Yếu tố khác, Tọa độ (vĩ độ), Tọa độ (kinh độ), Hình ảnh của bài đăng, Web]
Index: []

[0 rows x 32 columns]

In [3]:
with sqlite3.connect('output/real_estate.db') as conn:
    old_bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    old_onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [4]:
cleaned.duplicated().sum()

np.int64(248)

In [14]:
(old_onehousing_raw.shape[0] - old_onehousing_raw.duplicated(keep=False).sum()) == onehousing_raw.shape[0]
print(f'old_onehousing_raw shape: {old_onehousing_raw.shape[0]}')
print(f'onehousing_raw shape: {onehousing_raw.shape[0]}')
print(f'Num of duplicated rows: {old_onehousing_raw.duplicated(keep=False).sum()}')

old_onehousing_raw shape: 6836
onehousing_raw shape: 4494
Num of duplicated rows: 2257

In [6]:
cleaned[cleaned['Đơn giá xây dựng'].isna()]['Web']

8763    Onehousing
8768    Onehousing
8776    Onehousing
8777    Onehousing
8780    Onehousing
8781    Onehousing
8783    Onehousing
8788    Onehousing
Name: Web, dtype: object

In [10]:
cleaned['Thời điểm giao dịch/rao bán'] = pd.to_datetime(cleaned['Thời điểm giao dịch/rao bán'])

start_date = datetime.datetime(2025, 10, 1)
end_date = datetime.datetime(2026, 2, 11)

cleaned[(cleaned['Thời điểm giao dịch/rao bán'] >= start_date) & (cleaned['Thời điểm giao dịch/rao bán'] <= end_date)]

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,...,Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
0,Thành phố Hồ Chí Minh,Quận 8,Phường 1,Đường Dương Bá Trạc,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,2025-12-23,None,7.500000e+09,...,1,Chữ nhật,3.5,10.00,Đất ở,"Diện tích 58,9m² công nhận đủ,\r\nNgang 3,9m d...",10.745337,106.690188,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
1,Thành phố Hồ Chí Minh,Quận Gò Vấp,Phường 9,Đường Lê Văn Thọ,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,2025-12-25,None,6.550000e+09,...,1,Chữ nhật,5.0,10.00,Đất ở,Khu cao tầng hẻm xe hơi ngang hơn 5m hiếm.\r\n...,10.846724,106.656586,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
2,Thành phố Hà Nội,Quận Tây Hồ,Phường Xuân La,Đường Xuân La,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,2025-12-23,None,2.800000e+10,...,1,Chữ nhật,5.0,10.00,Đất ở,GIÁ 28TỶ - NGOẠI GIAO ĐOÀN - XUÂN LA - TÂY HỒ ...,21.064891,105.806182,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
3,Thành phố Hà Nội,Quận Long Biên,Phường Phúc Lợi,Đường Phúc Lợi,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,2025-12-28,None,6.700000e+09,...,2,Chữ nhật,2.5,15.00,Đất ở,"Nhà lô góc 2 mặt thoáng, sáng mát tự nhiên. Di...",21.038674,105.934373,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
4,Thành phố Hà Nội,Quận Tây Hồ,Phường Phú Thượng,Đường Phú Thượng,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,2025-12-30,None,1.180000e+10,...,1,Chữ nhật,4.5,100.00,Đất ở,RẺ NHẤT KHU VỰC. CẦN BÁN NHÀ DÂN XÂY 3T 60M2. ...,21.083858,105.808483,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15997,Thành phố Hà Nội,Huyện Thanh Trì,Xã Tả Thanh Oai,Đường Tả Thanh Oai,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Duong-T...,Đang giao dịch,2026-01-20,None,5.300000e+09,...,1,Chữ nhật,2.0,304.55,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
15998,Thành phố Hà Nội,Quận Long Biên,Phường Việt Hưng,Nguyễn Khắc Viện,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Nguyen-...,Đang giao dịch,2026-01-20,None,2.450000e+10,...,1,Chữ nhật,8.0,30.00,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
15999,Thành phố Hà Nội,Quận Hoàng Mai,Phường Định Công,Đường Kim Giang,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Duong-K...,Đang giao dịch,2026-01-20,None,1.700000e+10,...,1,Chữ nhật,2.0,50.00,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
16000,Thành phố Hà Nội,Quận Long Biên,Phường Long Biên,Đàm Quang Trung,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Dam-Qua...,Đang giao dịch,2026-01-20,None,1.190000e+10,...,1,Chữ nhật,3.1,200.00,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
16001,Thành phố Hà Nội,Huyện Gia Lâm,Xã Cổ Bi,Đường Cổ Bi,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Duong-C...,Đang giao dịch,2026-01-20,None,1.540000e+10,...,1,Chữ nhật,6.1,30.00,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing

In [1]:
from main import clean
clean()

Adding raw Batdongsan data to the database at 2026-02-12 18:13:23.116696...
Finished adding raw data of Batdongsan at 2026-02-12 18:13:42.584086!
Adding raw Onehousing data to the database at 2026-02-12 18:13:42.584086...
Finished adding raw data of Onehousing at 2026-02-12 18:13:43.040432!
Cleaning Batdongsan data at 2026-02-12 18:13:43.040432...
Dropped 0 duplicated raw rows for Batdongsan.
Ground truth file not found.
Dropped 21889 duplicated rows for Batdongsan.
Dropped 94155 NaN rows for Batdongsan.
Final number of rows for Batdongsan: 11681
Finished cleaning Batdongsan data at 2026-02-12 18:42:12.988790!
Cleaning Onehousing data at 2026-02-12 18:42:12.991328...
[OneHousing] Data cleaning completed.
Dropped 0 duplicated rows for Onehousing.
Dropped 0 NaN rows for Onehousing.
Final number of rows for Onehousing: 4113
Finished cleaning Onehousing data at 2026-02-12 18:42:14.011092!
Finished filling NaN in 0.3841872215270996 seconds.
Finished adding data to the database at 2026-02-12 18:42:15.970608!

# Xuất file chạy lại

In [1]:
import pandas as pd
import sqlite3
from commons.config import *
from main import clean
import time

In [40]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)

bds_raw.to_csv(DETAILS_CSV_PATH['Batdongsan'], encoding='utf-8-sig', index=False)
onehousing_raw.to_csv(DETAILS_CSV_PATH['Onehousing'], encoding='utf-8-sig', index=False)

In [2]:
clean()

Creating database tables...
Finished creating database!
Adding raw Batdongsan data to the database at 2026-02-27 11:07:13.482374...
Finished adding raw data of Batdongsan at 2026-02-27 11:07:23.863921!
Adding raw Onehousing data to the database at 2026-02-27 11:07:23.863921...
Finished adding raw data of Onehousing at 2026-02-27 11:07:23.998303!
Cleaning Batdongsan data at 2026-02-27 11:07:23.998303...
Dropped 0 duplicated raw rows for Batdongsan.
Ground truth file not found.
Dropped 21889 duplicated rows for Batdongsan.
Dropped 94155 NaN rows for Batdongsan.
Final number of rows for Batdongsan: 11681
Finished cleaning Batdongsan data at 2026-02-27 11:16:44.301812!
Cleaning Onehousing data at 2026-02-27 11:16:44.301812...
[OneHousing] Data cleaning completed.
Dropped 0 duplicated rows for Onehousing.
Dropped 0 NaN rows for Onehousing.
Final number of rows for Onehousing: 4113
Finished cleaning Onehousing data at 2026-02-27 11:16:44.665050!
Finished filling NaN in 0.20035099983215332 seconds.
Finished adding data to the database at 2026-02-27 11:16:45.500402!

# Test db theo scrape mới

In [2]:
# Old rules of saving NaN values
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw_old = pd.read_sql('SELECT * FROM bds_raw', conn)
    oh_raw_old = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned_old = pd.read_sql('SELECT * FROM cleaned', conn)

In [3]:
# New rules of saving NaN values
with sqlite3.connect('output/real_estate_test.db') as conn:
    bds_raw_new = pd.read_sql('SELECT * FROM bds_raw', conn)
    oh_raw_new = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned_new = pd.read_sql('SELECT * FROM cleaned', conn)

## Check Onehousing raw

In [5]:
oh_raw_new.duplicated().sum()
oh_raw_new = oh_raw_new[oh_raw_new['property_description'] != 'nanval']

In [6]:
oh_raw_id_dict = oh_raw_new['property_id'].value_counts().to_dict()
check_list = []
for k, v in oh_raw_id_dict.items():
    if v > 1:
        check_list.append(k)
print(len(check_list))
print(check_list)

1
['QMJRLZ']

In [8]:
yo = oh_raw_new.copy()
yo['city'] = yo['city'].str.strip()
yo['district'] = yo['district'].str.strip()
yo[yo['property_id'] == 'QMJRLZ']

for col in oh_raw_new.columns:
    first_id = yo[yo['property_id'] == 'QMJRLZ'].index[0]
    second_id = yo[yo['property_id'] == 'QMJRLZ'].index[1]
    if yo.loc[first_id, col] != yo.loc[second_id, col]:
        print(col)
        print(yo.loc[first_id, col])
        print(yo.loc[second_id, col])

unit_price
235 triệu/m²
137 triệu/m²
features
Hướng mặt tiền: Đông - 10.84m; Số tầng: 3; Diện tích: 106.1 m²
Hướng mặt tiền: Đông - 10.84m; Số tầng: 3; Diện tích: 182.7 m²
property_description
Bán nhà mặt ngõ cách Đê Trần Khát Chân 10m, Q. Hai Bà Trưng, diện tích 106.1m² x 3 tầng Nhà mặt tiền 10.84m, hướng Đông, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 106.1m² với tổng diện tích xây dựng 500m²... Nhà mặt tiền 10.84m, hướng Đông, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 10m... Kết cấu bao gồm: 3 tầng cao ...
Bán nhà mặt ngõ cách Đê Trần Khát Chân 10m, Q. Hai Bà Trưng, diện tích 182.7m² x 3 tầng Nhà mặt tiền 10.84m, hướng Đông, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 182.7m² với tổng diện tích xây dựng 500m²... Nhà mặt tiền 10.84m, hướng Đông, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 10m... Kết cấu bao gồm: 3 tầng cao ...

## Check BDS raw

In [163]:
bds_raw_id_dup = bds_raw_new['id'].value_counts().to_dict()
checklist_bds = []

for k,v in bds_raw_id_dup.items():
    if v > 1:
        checklist_bds.append(k)

print(len(checklist_bds))

19024

## Check cleaned

In [10]:
oh_cleaned = cleaned_new[cleaned_new['Web'] == 'Onehousing']
oh_cleaned.duplicated().sum()

np.int64(0)

In [11]:
oh_cleaned['id'] = oh_cleaned['Nguồn thông tin'].str.split('.').str[-1]
id_dup = oh_cleaned['id'].value_counts().to_dict()

In [12]:
checklist_cleaned = []
for k, v in id_dup.items():
    if v > 1:
        checklist_cleaned.append(k)
print(len(checklist_cleaned))

45

In [13]:
id = checklist_cleaned[44]
print(oh_cleaned[oh_cleaned['id'] == id].shape[0])
first_id = oh_cleaned[oh_cleaned['id'] == id].index[0]
second_id = oh_cleaned[oh_cleaned['id'] == id].index[1]

for col in oh_cleaned.columns:
    if oh_cleaned.loc[first_id, col] != oh_cleaned.loc[second_id, col]:
        print(col)
        print(oh_cleaned.loc[first_id, col])
        print(oh_cleaned.loc[second_id, col])
        print(id)
oh_cleaned[oh_cleaned['id'] == id]

2
Giá rao bán/giao dịch
85000000000.0
90000000000.0
JMOPT3
Giá ước tính
83300000000
88200000000
JMOPT3
Đơn giá xây dựng
4000000.0
0.0
JMOPT3

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,...,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web,id
11698,Thành phố Hà Nội,Quận Đống Đa,Phường Văn Chương,Tôn Đức Thắng,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Ton-Duc...,Đang giao dịch,20/01/2026,nanval,8.500000e+10,...,Chữ nhật,6.1,200.0,Đất ở,nanval,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing,JMOPT3
13927,Thành phố Hà Nội,Quận Đống Đa,Phường Văn Chương,Tôn Đức Thắng,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Ton-Duc...,Đang giao dịch,20/01/2026,nanval,9.000000e+10,...,Chữ nhật,6.1,200.0,Đất ở,nanval,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing,JMOPT3

- Các ID có đơn giá xây dựng thay đổi mặc dù các thông tin khác giống hệt: 2TPTCU, R4FRLY, LQTI8R, 081ZHX, 1CJ7BU, CDCGU6, BA6JAL, IHXIXJ, IFY0V8, BXACRJ, NYPEXU, OTEUAF, UMC7GM, TRJOM0, FZ5MRV, BG7IJ9, JJUPWP, DG38A8, VE23D5, YITFNR, HEJKTD
- ID F2JSXC, GKLXKW, JMOPT3 có thông tin về giá rao bán/giao dịch, giá ước tính và đơn giá xây dựng khác nhau. Tuy nhiên, đơn giá xây dựng vốn không dựa vào 2 giá trị kia để tính toán
- ID CC4W2Q có số mặt tiền tiếp giáp khác nhau trong khi các thông tin khác giống nhau 
- ID Y3Q79G có số mặt tiền tiếp giáp khác nhau, khác cả các thông tin về giá cả nhưng những thông tin này vốn irrelevant

# Sửa bds_cleaned theo rule mới

In [1]:
import sqlite3
import pandas as pd
import re
from rapidfuzz import fuzz

with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

bds_raw.drop_duplicates(subset='description', inplace=True)
bds_raw.reset_index(drop=True, inplace=True)

In [2]:
bds_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122089 entries, 0 to 122088
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             122089 non-null  object
 1   url            122089 non-null  object
 2   title          122089 non-null  object
 3   short_address  122089 non-null  object
 4   address_parts  122089 non-null  object
 5   latitude       122089 non-null  float64
 6   longitude      122089 non-null  float64
 7   main_info      122089 non-null  object
 8   description    122089 non-null  object
 9   other_info     122089 non-null  object
 10  image_urls     122089 non-null  object
dtypes: float64(2), object(9)
memory usage: 10.2+ MB

## Tổng diện tích sàn

In [3]:
def extract_building_area(row):
    construction_area = DataCleaner.extract_construction_area(row)
    num_floors = DataCleaner.extract_num_floors(row)
    text = DataCleaner.clean_description_text(str(row.get("description") or "").lower().strip())

    patterns = [
        r"(?i)diện\s+tích\s+sàn(?:\s+\S+){0,5}?\s+(\d+(?:[.,]\d+)?)\s*m[²2]",
        r"(?i)\bsàn(?:\s+\S+){0,5}?\s+(\d+(?:[.,]\d+)?)\s*m[²2]",
        r"(?i)(\d+(?:[.,]\d+)?)\s*m[²2](?:\s+\S+){0,5}?\s+diện\s+tích\s+sàn",
        r"(?i)(\d+(?:[.,]\d+)?)\s*m[²2](?:\s+\S+){0,5}?\s+sàn",
        r"(?i)diện\s+tích\s+sử\s+dụng(?:\s+\S+){0,5}?\s+(\d+(?:[.,]\d+)?)\s*m[²2]",
        r"(?i)(\d+(?:[.,]\d+)?)\s*m[²2](?:\s+\S+){0,5}?\s+diện\s+tích\s+sử\s+dụng",
        r"(?i)dtsd:?(?:\s+\S+){0,5}?\s+(\d+(?:[.,]\d+)?)\s*m[²2]",
        r"(?i)(\d+(?:[.,]\d+)?)\s*m[²2](?:\s+\S+){0,5}?\s+dtsd",
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            try:
                result = float(match.group(1).replace(",", "."))
                return result
            except ValueError:
                continue  

    if construction_area is not None and num_floors is not None:
        # If building area is not found in textual evidence, fallback to formula: Bulding area = Construction area x Number of floors 
        return round(construction_area * num_floors, 2)

    return None

def extract_construction_area(row):
    text = DataCleaner.clean_description_text(str(row.get("description") or "").lower().strip())
    land_area = DataCleaner.extract_total_area(row)

    # Tìm diện tích thổ cư/đất ở trong bài theo từ khóa              
    m = r"\b(\d{1,3}(?:[.,]\d{1,2})?)\s?m(?:²|2)(?:\s?\([^)]+\))?\s?(?:full\s)?(?:thổ cư|đất ở)"
    m2 = r"(?:thổ cư|đất ở|full\s?thổ cư)[\s:.,\-–]{0,3}(\d{1,3}(?:[.,]\d{1,2})?)\s?m(?:²|2)"

    if m in text:
        return round(float(m.group(1).replace(",", ".")), 2)
    elif m2 in text:
        return round(float(m2.group(1).replace(",", ".")), 2)
    
    # Tìm diện tích xây dựng
    

    # Trong trường hợp không tìm được diện tích thổ cư/đất ở cụ thể trong bài, mặc định diện tích xây dựng = diện tích đất
    kws = ["full thổ cư", "thổ cư 100%", "thổ cư hoàn toàn", "toàn bộ thổ cư", "thổ cư toàn bộ"]
    for kw in kws:
        if kw in text:
            return land_area

    matches = re.findall(r"\b\w+\s+thổ cư\s+\w+\b", text, re.IGNORECASE)
    for match in matches:
        for kw in kws:
            score = fuzz.ratio(match.lower(), kw.lower())
            if score > 55:
                return land_area       
    
    not_residential_land = ["đất trồng, đất vườn"]
    for keyword in not_residential_land:
        if keyword not in text:
            return land_area
        
    return None

In [5]:
def extract_dtxd(text):
    text = text.lower()
    # print(text)
    # print('\n------\n')
    dtxd = [r'(?:dtxd|dt xây dựng|diện tích xd|diện tích xây dựng)\s*\D{0,6}\s*(\d+(?:\s*(?:,|\.|m)\s*\d+)?)\s*m?\s*(?:x|\*)\s*(\d+(?:\s*(?:,|\.|m)\s*\d+)?)\s*m?', r'(?:dtxd|dt xây dựng|diện tích xd|diện tích xây dựng)\s*\D{0,6}\s*(\d+(?:\s*(?:,|\.|m)\s*\d+)?)\s*(?:m|/)']
    dtxd_new = [r'(?:dtxd|dt xây dựng|diện tích xd|diện tích xây dựng) *\D{0,6}\ *(\d+(?: *(?:,|\.|m) *\d+)?) *m? *(?:x|\*) *(\d+(?: *(?:,|\.|m) *\d+)?) *m?', r'(?:dtxd|dt xây dựng|diện tích xd|diện tích xây dựng) *\D{0,6} *(\d+(?: *(?:,|\.|m) *\d+)?) *(?:m|/)']
    for pat in dtxd_new:
        ca = re.search(pat, text)
        if ca:
            try:
                result = float(ca.group(1).replace(',', '.').replace('m', '.')) * float(ca.group(2).replace(',', '.').replace('m', '.'))
                if result <= 2000:
                    return result 
                return None
            except:
                result = float(ca.group(1).replace(',', '.').replace('m', '.'))
                if result <= 2000:
                    return result
                return None
            # area = ca.group(1).replace(',', '.').replace('m', '.')
            # try:
            #     area = float(area)
            #     return area
            # except:
            #     area_mul = re.search(r'(\d+(?:\s*(?:,|.|m)\s*\d+)?)\s*(?:x|*)\s*(\d+(?:\s*(?:,|.|m)\s*\d+)?)', area)
            #     if area_mul:
            #         return float(area_mul.group(1)) * float(area_mul.group(2))

# bds_raw['construction area'] = bds_raw['description'].apply(extract_dtxd)
# bds_raw['construction area'].notna().sum()

In [2]:
from Batdongsan.cleaning import DataCleaner

extract_building_area = DataCleaner.extract_building_area

bds_raw['building area'] = bds_raw.apply(extract_building_area, axis=1)
print(f'{bds_raw["building area"].notna().sum()} / {bds_raw.shape[0]}')

103797 / 122089

In [6]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
bds_raw[(bds_raw['building area'] < 5000) & (bds_raw['building area'] >= 3000)][['description', 'main_info', 'other_info', 'building area']]

,description,main_info,other_info,building area
22,"Chủ em cần bán căn nhà đang khai thác dòng tiền siêu khủng tại đường Nguyễn Thị Thập - 1 con đường thương hiệu vô cùng đắt đỏ... Trung tâm Quận 7, Khu dân cư dân trí cao nhộn nhịp, đi đâu cũng gần, cũng ăn uống mua sắm được hết, sở hữu để kinh doanh sẽ mang lại dòng tiền siêu khủng cho anh/ chị.\r\n- DT: 14m x 30m 352m².\r\n- Kết cấu: Hầm + trệt + 7 lầu + thang máy - 85 CHDV đang full.\r\n- Đường: Hẻm 2 xe hơi quay đầu.\r\n- Khai thác: 600tr/tháng\r\n- Cam kết sổ hồng trung thực, pháp lý rõ ràng, sang tên trong ngày nha.\r\n- Giá: 95 tỷ.\r\nLH:\r\n0909 679 ***\r\n- Dư Huỳnh\r\n\r\nCam kết với khách hàng:\r\n- Hiện tại Cty dư có hơn 29.000 SP nhà phó phân khúc cao cấp rãi đều toàn TP HCM, quý anh chị sẽ được tham khảo và được tụi em tư vấn miễn phí để tìm căn nhà ưng ý với mức giá hợp lý.\r\n- Mình làm việc dựa vào uy tín hàng đầu, tin thật, nhà thật, chủ thật... Biết ơn các anh/chị khách hàng đã thiện chí làm việc cùng em.","[{""title"": ""Khoảng giá"", ""value"": ""95 tỷ"", ""ext"": ""~190 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""500 m²"", ""ext"": ""8 tầng""}, {""title"": ""Phòng ngủ"", ""value"": ""30 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""04/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""19/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""37850935"", ""ext"": null}]","{""Khoảng giá"": ""95 tỷ"", ""Diện tích"": ""500 m²"", ""Số phòng ngủ"": ""30 phòng"", ""Số phòng tắm, vệ sinh"": ""20 phòng"", ""Số tầng"": ""8 tầng"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}",4000.0
1924,"Vị trí trung tâm: Ngay điểm giao Q11, Q5, Q10 (Nguyễn Chí Thanh giao Nguyễn Thị Nhỏ).\r\nDiện tích đất ~790m², kết cấu 5 tầng (tổng diện tích sử dụng ~ 4000 m²), chỉ 62 tỷ.\r\nThu nhập cho thuê hiện tại ~300 triệu/tháng (nhà cũ nên có thể cải tạo nhẹ để đạt 500 - 600 triệu/ 1 tháng).\r\nDòng tiền đủ trả lãi ngân hàng và còn dư (Hệ số cho thuê hơn 8%/ 1 năm trên giá trị tòa).\r\nPhù hợp nhà đầu tư dài hạn, có sẵn giấy phép cho thuê phòng, đủ điều kiện PCCC lâu năm.\r\nGiá bán xử lý nhanh, thấp hơn thị trường 3050%.\r\nHoa hồng môi giới 1%.\r\nInbox Asia Legal Group (Mr. Ẩn) để nhận thông tin chi tiết.\r\n0945 009 ***\r\n.","[{""title"": ""Khoảng giá"", ""value"": ""62 tỷ"", ""ext"": ""~78,48 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""790 m²"", ""ext"": ""5 tầng""}, {""title"": ""Ngày đăng"", ""value"": ""31/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""15/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44932889"", ""ext"": null}]","{""Khoảng giá"": ""62 tỷ"", ""Diện tích"": ""790 m²"", ""Số tầng"": ""5 tầng"", ""Đường vào"": ""6 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng""}",4000.0
2929,"Thật 100% tốt nhất 123 triệu/m² (Trừ tiền xây dựng dinh thự) 1215m² (30x45m) hồ bơi cổ điển Thảo Điền - Võ Trường Toản, Quận 2.\r\n\r\n- Diện tích: 1215m², 30x45m. Nhà có 8 phòng, 1 hầm 3 lầu, thang máy.\r\n\r\nGiá: 199 tỷ thương lượng ít.\r\n- Pháp lý: Sổ hồng chính chủ 1 đời riêng công chứng ngay.\r\n\r\nVị trí: Thảo Điền, Võ Trường Toản, Quận 2. Ngay Song Hành chạy vào 200m, bảo đảm 100% không ngập lụt vào mùa mưa.\r\n\r\nVà những căn biệt thự đẳng cấp giá mềm cho quý tộc lựa chọn.\r\n\r\n1. Thật 100% 1200m² thổ cư sát Vincom Thảo Điền hồ bơi triệu/m² chỉ 200 tỷ biệt thự công nhận: 1200m² thổ cư hồ bơi, sân vườn, Q. 2, DT 30x40m. Hầm 3 tầng.\r\n\r\n2/ Biệt thự 2000m² sàn 50x20m. Vuông công nhận 940m² khu ở nguyên thủ quốc gia ngay Võ Trường Toản Thảo Điền Q. 2.\r\nDiện tích: 50x20m, vuông 940m², 2000m² sàn.\r\nKết cấu: Hầm 3 lầu áp mái. Có Thang máy cao cấp ngay Massteri An Phú gần Võ Trường Toản. Thảo Điền Quận 2.\r\nGiá: 199 tỷ.","[{""title"": ""Khoảng giá"", ""value"": ""199 tỷ"", ""ext"": ""~163,79 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""1.215 m²"", ""ext"": ""4 tầng""}, {""title"": ""Phòng ngủ"", ""value"": ""8 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""03/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""18/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""34890545"", ""ext"": null}]","{""Khoảng giá"": ""199 tỷ"", ""Diện tích"": ""1.215 m²"", ""Số phòng ngủ"": ""8 phòng"", ""Số phòng tắm, vệ sinh"": ""9 phòng"", ""Số tầng"": ""4 tầng"", ""Đường vào"": ""10 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Cao cấp""}",4860.0
3957,"Bán nhà vườn mặt tiền đường nhựa, sát khu du lịch biển Tân Thành, Gò Công Đông, tỉnh Tiền Giang cũ (nay là tỉnh Đồng Tháp).\r\n\r\n+ Tổng diện tích đất: 3127m² (ngang 34m, nở hậu 36m x dài 89m).\r\n+ Loại đất: Đất vườn CLN có 300m đất thổ cư.\r\n+ Loại nhà: Nhà cấp 4 xây chắc chắn, kiên cố, 4 phòng ngủ, 2 toilets. Nhà thoáng mát. Sân rộng rãi,...\r\n\r\n+ Pháp lý: Sổ đầy đủ, đất sạch không mồ mả, không tranh chấp, không nằm trong quy hoạch, mua bán công chứng sang tên hợp pháp.\r\n+ Giá bán: 7,2 tỷ. Thương lượng.\r\n\r\n+ Đất đang trồng cây ăn trái (nhãn xuồng cơm vàng đã thu hoạch nhiều năm, ngoài ra còn chuối, xài, mận... ). Đất rộng rãi thoáng mát, xung quanh rào tường chắc chắn, đất nở hậu cạnh góc vuông.\r\n+ Sát bên khu du lịch biển Tân Thành.\r\n+ Tiện ích đầy đủ: Uỷ ban, chợ, trường học, trạm y tế, sân banh, nhà hàng, KS...\r\n+ Thích hợp ở làm nhà vườn, nhà nghỉ dưỡng, homestay, đầu tư sinh lời, mua làm của...\r\n\r\n+ Mặt tiền trục đường tỉnh ĐT862 nhựa, xã Tân Thành, Gò Công Đông, tỉnh Tiền Giang cũ (nay là tỉnh Đồng Tháp). Phía trước là dự án đường tỉnh ĐT864 (đường ven biển miền tây) đi dọc qua các tỉnh miền Tây đã khởi công làm từ đầu năm 2025.\r\n\r\nĐể xem chi tiết, khách vui lòng liên hệ: Gặp Nguyễn Hoà. ĐT\r\n0949 767 ***\r\n.\r\nCảm ơn!","[{""title"": ""Khoảng giá"", ""value"": ""7,2 tỷ"", ""ext"": ""~2,3 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""3.127 m²"", ""ext"": ""Mặt tiền 34 m""}, {""title"": ""Phòng ngủ"", ""value"": ""4 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""27/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""11/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""43512894"", ""ext"": null}]","{""Khoảng giá"": ""7,2 tỷ"", ""Diện tích"": ""3.127 m²"", ""Số phòng ngủ"": ""4 phòng"", ""Số phòng tắm, vệ sinh"": ""2 phòng"", ""Số tầng"": ""1 tầng"", ""Mặt tiền"": ""34 m"", ""Đường vào"": ""8 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng""}",3127.0
8009,"- Bán tòa nhà ngay mặt tiền Nơ Trang Long, P. 12, Q. Bình Thạnh.\r\n- Diện tích: 11 x 47m.\r\n- Kết cấu: Hầm + 6 tầng.\r\n- Hợp đồng thuê: 450 triệu/tháng.\r\n- Tuyến đường lớn, cực kỳ sầm uất.\r\n- Giá bán: 55 tỷ TL.\r\n- Liên hệ ngay:\r\n0834 766 ***\r\nTư Hậu.","[{""title"": ""Khoảng giá"", ""value"": ""55 tỷ"", ""ext"": ""~106,38 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""517 m²"", ""ext"": ""Mặt tiền 11 m""}, {""title"": ""Ngày đăng"", ""value"": ""24/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""08/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44882692"", ""ext"": null}]","{""Khoảng giá"": ""55 tỷ"", ""Diện tích"": ""517 m²"", ""Số tầng"": ""6 tầng"", ""Mặt tiền"": ""11 m""}",3102.0
9988,"Khách sạn Đặng Tất, ngang 17m hẻm ô tô, cách biển Hòn Chồng 200m.\r\n\r\nGiá: 55 tỷ.\r\n\r\n+ Có: 48 phòng, 9 tầng, có tầng hầm { hoàn công bài bản.\r\n\r\n+ Vị trí: Hẻm Đặng Tất, P Vĩnh Hải, TP Nha Trang, tỉnh Khánh Hòa.\r\n\r\n+ Diện tích: 408m² (228m² ODT).\r\n\r\n+ Hướng Đông / ngang: 17m.\r\n\r\n+ Bê tông ô tô, rộng: 7 - 8m.\r\n\r\n+ Cách Bắc Sơn: 120m / Đặng Tất: 80m / Sân bay Cam Ranh: 35km.","[{""title"": ""Khoảng giá"", ""value"": ""55 tỷ"", ""ext"": ""~134,8 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""408 m²"", ""ext"": ""9 tầng""}, {""title"": ""Phòng ngủ"", ""value"": ""48 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""04/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""19/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44467378"", ""ext"": null}]","{""Khoảng giá"": ""55 tỷ"", ""Diện tích"": ""408 m²"", ""Số phòng ngủ"": ""48 phòng"", ""Số tầng"": ""9 tầng"", ""Hướng nhà"": ""Đông"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng""}",3672.0
10780,"Cần bán tòa nhà Building trong ngõ, vài bước chân ra mặt phố Võ Chí Công, phường Xuân La, quận Tây Hồ, HN. Chủ gửi bán giá 110 tỷ. Phong thủy cực thịnh.\r\n\r\n- Diện tích: 346m². Xây 10 tầng, mặt tiền 16m. Gồm 33 phòng khách sạn + 15 căn hộ.\r\n\r\n* Vị trí: Ngõ vào xe ba gác, cách mặt đường lớn Võ Chí Công chỉ vài bước chân. Trước nhà rộng thoáng, yên tĩnh. Là thế đất ngọa hổ tàng long hiếm tìm, có 1 0 2.\r\n+ Hiện đang cho 1 đơn vị thuê làm khách sạn. Doanh thu trung bình 400 - 500 triệu/ tháng.\r\n\r\n* Thiết kế: 1 tầng hầm, 9 tầng nổi:\r\n- Tầng hầm: Để xe máy.\r\n- Tầng 1: Sảnh lễ tân, phòng giám đốc, nhà hàng.\r\n- Tầng 2 - 6: Mỗi tầng 6 phòng khách sạn cao cấp + 2 căn hộ hạng sang (2 phòng ngủ, khách, bếp.. ).\r\n- Tầng 7: 4 căn hộ.\r\n- Tầng 8: 3 phòng khách sạn + 1 căn hộ.\r\n- Tầng 9: Sân thượng.\r\n\r\n* Sổ đỏ chính chủ, sẵn sàng giao dịch ngay.\r\n* Giá bán: 110 tỷ.\r\n\r\n* Liên hệ: Em Phương\r\n0975 771 ***\r\n. Tư vấn và hỗ trợ xem nhà miễn phí. Miễn tiếp MG, TG.\r\nXin cảm ơn!","[{""title"": ""Khoảng giá"", ""value"": ""110 tỷ"", ""ext"": ""~317,92 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""346 m²"", ""ext"": ""Mặt tiền 16 m""}, {""title"": ""Phòng ngủ"", ""value"": ""48 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""06/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""21/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""43245327"", ""ext"": null}]","{""Khoảng giá"": ""110 tỷ"", ""Diện tích"": ""346 m²"", ""Số phòng ngủ"": ""48 phòng"", ""Số phòng tắm, vệ sinh"": ""48 phòng"", ""Số tầng"": ""10 tầng"", ""Mặt tiền"": ""16 m"", ""Đường vào"": ""3 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Cơ bản""}",3460.0
11533,"Nhà lô góc 2 mặt tiền 600m², dòng tiền 180 - 200 triệu /tháng chỉ có 32 tỷ TL.\r\n\r\nDiện tích xây dựng 1000m² 4 tầng hiện có 50 phòng full nội thất dòng tiền 180 triệu đến 200 triệu một tháng.\r\n\r\nTiềm năng khai thác cho thuê vượt trội tại Long Thạnh Mỹ vị trí lô góc đắc địa.\r\n\r\nTọa lạc tại vị trí lô góc mặt tiền, thuộc khu vực vip nhất phường Long Thạnh Mỹ, căn nhà 4 tầng sở hữu quy mô lớn với 50 phòng đang khai thác ổn định, mang lại dòng tiền 180 - 200 triệu đồng/tháng.\r\n\r\nVị trí chiến lược, tương lai kết nối trực tiếp với đại đô thị Vinhomes, càng gia tăng giá trị khai thác cho thuê. Xung quanh là hệ thống tiện ích phong phú: Gần chợ, UBND, đại học, bách hóa đáp ứng đầy đủ nhu cầu sinh hoạt của người thuê.\r\n\r\nPhù hợp đầu tư dài hạn với dòng tiền vững chắc, tiềm năng tăng giá cao.\r\nChú ý: Sổ hồng chính chủ, chủ hợp tác mua bán công chứng nhanh và hỗ trợ khách vay nếu cần. Ngoài ra các thủ tục liên quan chủ luôn chủ động hỗ trợ khách hàng.\r\nThành Sơn chuyên nhà có dòng tiền tại Thủ Đức, vị trí gần các trường đại học và cao đẳng, đảm bảo luôn kín phòng với hệ thống PCCC đạt chuẩn, an ninh nghiêm ngặt và nguồn thu nhập ổn định, cao. Quý khách có nhu cầu vui lòng liên hệ:\r\n0383 692 ***\r\n.\r\n\r\nLH:\r\n0383 692 ***\r\nThành Sơn làm việc chính chủ, không liên kết môi giới, xin cảm ơn!","[{""title"": ""Khoảng giá"", ""value"": ""32 tỷ"", ""ext"": ""~53,33 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""600 m²"", ""ext"": ""Mặt tiền 22 m""}, {""title"": ""Ngày đăng"", ""value"": ""27/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""11/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44907716"", ""ext"": null}]","{""Khoảng giá"": ""32 tỷ"", ""Diện tích"": ""600 m²"", ""Số tầng"": ""4 tầng"", ""Mặt tiền"": ""22 m"", ""Đường vào"": ""6 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng.""}",4000.0
14173,"- Diện tích: 30m x 39m, vuông đét.\r\n- DTCN: 1.120m².\r\n- Kết cấu: Nhà 3 tầng.\r\n- Vị trí: Nhà ngay trung tâm Quận 3, gần ngã 4 Lê Văn Sỹ và Trần Quang Diệu, gần chợ Nguyễn Văn Trỗi,...\r\n- Giá trị: Là quỹ đất hiếm và duy nhất, không có sản phẩm so sánh trong khu vực Trung Tâm Sài Gòn với mức giá siêu rẻ và hấp dẫn như căn này.\r\n- Pháp lý: Sổ hồng cá nhân.\r\n- Giá bán: 185 tỷ.\r\n\r\nXem nhà LH: Lê Minh -\r\n0913 275 ***\r\n- Làm việc chính chủ.\r\n- Cam kết sản phẩm thật, giá trị thật 100% - .","[{""title"": ""Khoảng giá"", ""value"": ""185 tỷ"", ""ext"": ""~165,18 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""1.120 m²"", ""ext"": ""Mặt tiền 30 m""}, {""title"": ""Ngày đăng"", ""value"": ""05/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""20/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""43439442"", ""ext"": null}]","{""Khoảng giá"": ""185 tỷ"", ""Diện tích"": ""1.120 m²"", ""Số tầng"": ""3 tầng"", ""Mặt tiền"": ""30 m"", ""Đường vào"": ""12 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng""}",3360.0
14899,"Mặt tiền VIP - ngay Khu Him Lam - Phạm Văn Đồng - TP Thủ Đức.\r\n\r\nVị trí mặt tiền kinh doanh đỉnh nhất Khu vực, đang cho thuê KD siêu thị, mặt tiền đường rộng 20m.\r\n\r\n- Diện tích 210m²: Ngang khủng 10x21m - DTXD 664m² (189m/1 sàn).\r\n\r\nNhà 5 tầng, chính chủ tự xây tâm huyết, mới 2020. Thang máy sịn sò.\r\n\r\nHiện tầng trệt + tầng 2 chủ đang cho thuê Siêu thị thuê full.\r\nTầng 3: 03 căn hộ chung cư 55m²/căn.\r\nTầng 4: Nguyên sàn là Căn hộ Doublex, hồ bơi.\r\nTầng 5: Sân thượng lớn: Trồng rau, nuôi gà.\r\n\r\n- Tổng dòng tiền trên 89tr/tháng.\r\n\r\n- Sổ hồng riêng, hoàn công chuẩn, CC ngay.\r\n\r\n- Liên hệ: Mr Cường BĐS Thủ Đức, gặp chính chủ chốt liền tay.","[{""title"": ""Khoảng giá"", ""value"": ""25,5 tỷ"", ""ext"": ""~121,43 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""210 m²"", ""ext"": ""Mặt tiền 10 m""}, {""title"": ""Phòng ngủ"", ""value"": ""6 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""05/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""20/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""43239758"", ""ext"": null}]","{""Khoảng giá"": ""25,5 tỷ"", ""Diện tích"": ""210 m²"", ""Số phòng ngủ"": ""6 phòng"", ""Số phòng tắm, vệ sinh"": ""6 phòng"", ""Số tầng"": ""5 tầng"", ""Mặt tiền"": ""10 m"", ""Pháp lý"": ""Sổ hồng riêng"", ""Nội thất"": ""Đầy đủ""}",3320.0
17810,"Bùi Thị Xuân, phường Bến Thành, Quận 1.\r\n- Diện tích: 12x25m.\r\n- Kết cấu: Hầm 11 tầng + sân thượng.\r\n- Thiết kế: 50 phòng.\r\n- Full nội thất, CN đang tự kinh doanh.\r\n- Giá: 115 tỷ.\r\n- Pháp lý tư nhân.\r\n- Vị trí khu vực chuyên kinh doanh khách sạn.\r\n* Liên hệ:\r\n0903 617 ***\r\ngặp KIM NGỌC để nhận thông tin chi tiết.","[{""title"": ""Khoảng giá"", ""value"": ""115 tỷ"", ""ext"": ""~383,33 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""300 m²"", ""ext"": ""Mặt tiền 12 m""}, {""title"": ""Ngày đăng"", ""value"": ""31/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""15/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""34837524"", ""ext"": null}]","{""Khoảng giá"": ""115 tỷ"", ""Diện tích"": ""300 m²"", ""Số tầng"": ""11 tầng"", ""Mặt tiền"": ""12 m""}",3300.0
20178,"- Hạ giá chỉ còn 79 tỷ còn thương lượng chính chủ\r\n- Bán bất động sản dòng tiền -.\r\nCần bán khách sạn 3 mặt tiền hẻm 7m Đường Phạm văn Đồng, P. Linh Đông, TP. Thủ Đức, TPHCM (cách phạm văn đồng 50m).\r\nDiện tích đất: 22m x 24m = 500m² (full thổ cư, ko lộ giới).\r\nHiện trạng: 1 hầm + 6 Tầng.\r\nVị trí: Ks ở vị trí 3 mặt tiền hẻm 7m (quy hoạch đường 16) cách mặt tiền đường Phạm Văn Đồng 50m, gần sông Sài Gòn, gần trường cao đẳng công nghệ thủ Đức, đi sân bay 10p.\r\nHiện đang khai thác.\r\nPhù hợp: Khai thác dòng tiền khách sạn, chuyển đổi khai thác căn hộ dịch vụ cao cấp, làm nhà hàng caffe - view sông, hàm rượu cao cấp, karaoke,. Vv.\r\nLH:\r\n0963 492 ***\r\nThắng.\r\n- Nhận kí gởi nhà đất.","[{""title"": ""Khoảng giá"", ""value"": ""79 tỷ"", ""ext"": ""~158 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""500 m²"", ""ext"": ""Mặt tiền 22 m""}, {""title"": ""Ngày đăng"", ""value"": ""02/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""17/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""43657784"", ""ext"": null}]","{""Khoảng giá"": ""79 tỷ"", ""Diện tích"": ""500 m²"", ""Số tầng"": ""6 tầng"", ""Mặt tiền"": ""22 m"", ""Đường vào"": ""7 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}",3000.0
27513,"Tôi cần bán khách sạn Nha Trang, đường Trần Quang Khải, cách biển vài trăm mét.\r\n- Hoạt động năm 2018.\r\n- Diện tích 160m² mặt tiền 10 mét.\r\n- 20 tầng, có 70 phòng.\r\n- Nhà hàng buffet, hồ bơi.\r\n- Pháp lý: PCCC, ANTT đầy đủ.\r\n- Sổ đỏ sở hữu lâu dài.\r\n- Giá bán: 80 tỷ (có thương lượng).\r\n* Anh chị quan tâm xin liên hệ:\r\n0868 674 ***\r\n- Phụng Nguyễn.\r\n\r\nTôi còn nhiều nguồn khách sạn, nhà phố đầu tư dòng tiền tốt, anh chị liên hệ để nhận thêm thông tin chi tiết nhé!\r\nXin chân thành cảm ơn!","[{""title"": ""Khoảng giá"", ""value"": ""80 tỷ"", ""ext"": ""~500 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""160 m²"", ""ext"": ""Mặt tiền 10 m""}, {""title"": ""Phòng ngủ"", ""value"": ""70 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""26/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""10/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""39914878"", ""ext"": null}]","{""Khoảng giá"": ""80 tỷ"", ""Diện tích"": ""160 m²"", ""Số phòng ngủ"": ""70 phòng"", ""Số phòng tắm, vệ sinh"": ""71 phòng"", ""Số tầng"": ""20 tầng"", ""Hướng nhà"": ""Nam"", ""Hướng ban công"": ""Nam"", ""Mặt tiền"": ""10 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}",3200.0

#

- Lớn hơn 5000
    - 4124: thổ cư 300m2 mà không lấy pattern này nên nó đang lấy diện tích là 6984.9 luôn
    - 22825: có để diện tích xây dựng 1200 mà sao không lấy lại lấy diện tích đất nhân số tầng
    - 43666: diện tích trên 300m, nhưng do diện tích trong main_info để là 3150 nên khi nhân lên 2 tầng biến tướng thành 6300
    - 57679: diện tích đất thì là 90.2, trong khi diện tích xây dựng 724.47? --> viết sai sao đấy, thêm điều kiện
    - 64317: tổng dtxd 855
    - 64658: có cái diện tích xây dựng 1000m nên chắc nó loại luôn
    - 85802: phần diện tích xây dựng nó ghi là 1200, lớn hơn diện tích đất * số tầng (194 * 6 = 1164) luôn
    - 90992: nhà c4 nhưng ghi số tầng là 4
    - 91825: 1400m thổ cư nhưng lấy diện tích đấy là 3200m nhân số tầng
    - 104682: 1.410,3m thổ cư nhưng lấy theo diện tích đất luôn
    - 107699: 400 mét thổ cư, căn nhà 300 mét vuông nhưng đang lấy diện tích đất
    - 109315: 300m thổ cư, biệt thự xây dựng 320m nhưng đang lấy diện tích đất
    - 116521: 550m thổ cư nhưng đang lấy diện tích đất
    - 119957: 1183m đất odt
- Lớn hơn 3000:
    - 3957: 300m đất thổ cư
    - 9988: 228m ODT
    - 62188: 350m thổ cư
    - 63275: Diện tích 108m 7 tầng mà sao tính ra 4200
    - 65545: thực tế sử dụng 1015m
    - 77785: 635m thổ cư
    - 90870: 228m ODT
    - 111411: DT sàn: 2.231,7m2
    - 113447: trên mảnh đất có ngôi nhà ngang 10 dài 13,5 thước, diện tích 135m2

In [18]:
bds_raw.loc[90992, 'url']

'https://batdongsan.com.vn/ban-nha-rieng-duong-vuon-lai-phuong-an-phu-dong-1/-c4-1300m-gan-cho-gia-ngop-25ty-pr44913918'