In [14]:
import pandas as pd
import sqlite3
import datetime

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [8]:
cleaned.shape

(10426, 32)

In [12]:
cleaned.duplicated().sum()

np.int64(4)

In [17]:
bds_raw.duplicated().sum()

np.int64(0)

In [24]:
cleaned[
    (cleaned["Đơn giá đất"].isnull()) &
    (cleaned["Web"] == "Onehousing")
].value_counts

<bound method DataFrame.value_counts of         Tỉnh/Thành phố Thành phố/Quận/Huyện/Thị xã   Xã/Phường/Thị trấn  \
6451  Thành phố Hà Nội                Quận Hà Đông      Phường Vạn Phúc
6452  Thành phố Hà Nội            Quận Bắc Từ Liêm     Phường Xuân Đỉnh
6453  Thành phố Hà Nội           Quận Hai Bà Trưng      Phường Vĩnh Tuy
6454  Thành phố Hà Nội                Quận Hà Đông        Phường Hà Cầu
6455  Thành phố Hà Nội                Quận Đống Đa   Phường Thịnh Quang
...                ...                         ...                  ...
8785  Thành phố Hà Nội                Quận Đống Đa   Phường Thịnh Quang
8786  Thành phố Hà Nội              Quận Long Biên     Phường Thạch Bàn
8787  Thành phố Hà Nội              Quận Hoàng Mai     Phường Tương Mai
8788  Thành phố Hà Nội               Huyện Gia Lâm             Xã Cổ Bi
8789  Thành phố Hà Nội              Quận Long Biên  Phường Thượng Thanh

            Đường phố Chi tiết  \
6451          Phố Lụa  Mặt ngõ
6452        Xuân Đỉnh  Mặt ngõ
6453         Kim Ngưu  Mặt ngõ
6454           Hà Trì  Mặt ngõ
6455       Thái Thịnh  Mặt ngõ
...               ...      ...
8785          Tây Sơn  Mặt ngõ
8786  Nguyễn Văn Linh  Mặt ngõ
8787   Nguyễn An Ninh  Mặt ngõ
8788      Đường Cổ Bi  Mặt ngõ
8789         Gia Quất  Mặt ngõ

                                                                                                    Nguồn thông tin  \
6451            https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Lua-100m--P--Van-Phuc--Q--Ha-Dong--TP--Ha-Noi.ULHEKO
6452      https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI
6453      https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Nguu-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.YWGUVT
6454                https://onehousing.vn/bds/Nha-mat-ngo-cach-Ha-Tri-20m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.IIWMDZ
6455       https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ
...                                                                                                             ...
8785          https://onehousing.vn/bds/Nha-mat-ngo-cach-Tay-Son-50m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.FAGEYE
8786  https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Van-Linh-30m--P--Thach-Ban--Q--Long-Bien--TP--Ha-Noi.UKYUK5
8787   https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-An-Ninh-70m--P--Tuong-Mai--Q--Hoang-Mai--TP--Ha-Noi.ICQFWY
8788                https://onehousing.vn/bds/Dat-nen-cach-Duong-Co-Bi-30m--X--Co-Bi--H--Gia-Lam--TP--Ha-Noi.72STTB
8789      https://onehousing.vn/bds/Nha-mat-ngo-cach-Gia-Quat-10m--P--Thuong-Thanh--Q--Long-Bien--TP--Ha-Noi.JFTPU2

     Tình trạng giao dịch Thời điểm giao dịch/rao bán Thông tin liên hệ  \
6451       Đang giao dịch                  20/01/2026              None
6452       Đang giao dịch                  20/01/2026              None
6453       Đang giao dịch                  20/01/2026              None
6454       Đang giao dịch                  20/01/2026              None
6455       Đang giao dịch                  20/01/2026              None
...                   ...                         ...               ...
8785       Đang giao dịch                  20/01/2026              None
8786       Đang giao dịch                  20/01/2026              None
8787       Đang giao dịch                  20/01/2026              None
8788       Đang giao dịch                  20/01/2026              None
8789       Đang giao dịch                  20/01/2026              None

      Giá rao bán/giao dịch  Giá ước tính Loại đơn giá (đ/m2 hoặc đ/m ngang)  \
6451           9.200000e+09    9016000000                               đ/m2
6452           1.700000e+10   16660000000                               đ/m2
6453           5.200000e+09    5096000000                               đ/m2
6454           1.850000e+10   18130000000                               đ/m2
6455           1.950000e+10   19110000000                               đ/m2
...                     ...           ...                                ...
8785           2.250000e+10   22050000000                               đ/m2
8786           6.900000e+09    6762000000                               đ/m2
8787           1.480000e+10   14504000000                               đ/m2
8788           1.540000e+10   15092000000                               đ/m2
8789           1.550000e+10   15190000000                               đ/m2

      Đơn giá đất Lợi thế kinh doanh  Số tầng công trình  Tổng diện tích sàn  \
6451          NaN               None                 5.0               169.5
6452          NaN               None                 6.0               241.8
6453          NaN               None                 4.5               115.2
6454          NaN               None                 4.0               306.0
6455          NaN               None                 6.0               213.6
...           ...                ...                 ...                 ...
8785          NaN               None                 7.0               504.0
8786          NaN               None                 5.0               153.0
8787          NaN               None                 3.0               159.3
8788          NaN               None                 0.0                 0.0
8789          NaN               None                 4.0               168.0

      Đơn giá xây dựng Năm xây dựng  Chất lượng còn lại  Diện tích đất (m2)  \
6451         8221171.0         None                0.85                33.9
6452         8221171.0         None                0.85                40.3
6453         8221171.0         None                0.85                25.6
6454         8221171.0         None                0.85                76.5
6455         8221171.0         None                0.85                35.6
...                ...          ...                 ...                 ...
8785         8221171.0         None                0.85                72.0
8786         8221171.0         None                0.85                30.6
8787         8221171.0         None                0.85                53.1
8788               NaN         None                 NaN               119.7
8789         8221171.0         None                0.85                42.0

      Kích thước mặt tiền (m)  Kích thước chiều dài (m)  \
6451                     7.80                      4.35
6452                     4.10                      9.83
6453                     1.20                     21.33
6454                     5.00                     15.30
6455                     3.40                     10.47
...                       ...                       ...
8785                     4.35                     16.55
8786                     6.50                      4.71
8787                     3.40                     15.62
8788                     6.85                     17.47
8789                     4.00                     10.50

      Số mặt tiền tiếp giáp Hình dạng  Độ rộng ngõ/ngách nhỏ nhất (m)  \
6451                      1  Chữ nhật                             2.0
6452                      1  Chữ nhật                             4.0
6453                      1  Chữ nhật                             2.0
6454                      1  Chữ nhật                             6.0
6455                      1  Chữ nhật                             3.0
...                     ...       ...                             ...
8785                      1  Chữ nhật                             2.0
8786                      1  Chữ nhật                             2.0
8787                      1  Chữ nhật                             3.0
8788                      1  Chữ nhật                             6.1
8789                      1  Chữ nhật                             6.1

      Khoảng cách tới trục đường chính (m) Mục đích sử dụng đất Yếu tố khác  \
6451                                 100.0                Đất ở        None
6452                                  50.0                Đất ở        None
6453                                 100.0                Đất ở        None
6454                                  20.0                Đất ở        None
6455                                  30.0                Đất ở        None
...                                    ...                  ...         ...
8785                                  50.0                Đất ở        None
8786                                  30.0                Đất ở        None
8787                                  70.0                Đất ở        None
8788                                  30.0                Đất ở        None
8789                                  10.0                Đất ở        None

      Tọa độ (vĩ độ)  Tọa độ (kinh độ)  \
6451        21.00101        105.866667
6452        21.00101        105.866667
6453        21.00101        105.866667
6454        21.00101        105.866667
6455        21.00101        105.866667
...              ...               ...
8785        21.00101        105.866667
8786        21.00101        105.866667
8787        21.00101        105.866667
8788        21.00101        105.866667
8789        21.00101        105.866667

                                                                                                                                                                                                                                                                              Hình ảnh của bài đăng  \
6451                                                          https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/355c72a5-37b5-4b62-819a-f1f34e64d071/2c9427839a4a2959019b2c413fa75633_CLONE/LIVING_ROOM/scaled_1000040570_1765975397648.jpg
6452   https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/eb81035f-a264-4aed-932c-e524bac4e5e5/2c9427839a4a2959019ba140fe0c7de0_CLONE/LIVING_ROOM/image_picker_0225B86C-1140-496C-9131-6DC827356E26-75883-00001587015572D0_1767937910623.jpg
6453                                                          https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/62ea34f7-62ce-4f11-92c8-cd8d8c9ca823/2c9427839a4a2959019b30c1bfac58c6_CLONE/LIVING_ROOM/scaled_1000060304_1766050118802.jpg
6454                                                          https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8ebf97a2-39ac-491a-a797-aad2e820c127/2c9427839a4a2959019b48e5eb8d5f0c_CLONE/LIVING_ROOM/scaled_1000060911_1766455083168.jpg
6455   https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8995d755-c3d8-4b33-9b79-39c28c273d4f/2c9427839a4a2959019ba138a6847ddd_CLONE/LIVING_ROOM/image_picker_2E3A0736-3D43-4694-BD18-B10DAE346EF8-88338-00002DF9C82EA189_1767937353914.jpg
...                                                                                                                                                                                                                                                                                             ...
8785  https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/7b4cb4a2-6aa4-4f46-935a-ddc1e81d81bb/2c94211a9a4a2a77019c1260721a2a1c_CLONE/LOCAL_STREET/image_picker_09C8575E-742B-4DE7-9B25-63AB78F8C01E-67341-000024347B807E2B_1769835303056.jpg
8786    https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/2f84c8ac-e71a-4147-9fbf-df15f43989be/2c9427839a4a2959019c12175f6d27af_CLONE/LIVING_ROOM/image_picker_6594C502-A8DD-4936-9386-A1AD177BF810-5835-0000024A45CF6387_1769836993880.jpg
8787   https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/4478e20a-495f-4cfc-a415-cf9c16ff75eb/2c9427839a4a2959019c1d246ead2a23_CLONE/LIVING_ROOM/image_picker_5CF22A6A-E5A8-40CE-A43A-CA96036DC30B-43246-0000188C86067EA1_1770018021073.jpg
8788                                                         https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/c3ffa272-c543-431c-ae9f-6a137457f08f/2c9427839a4a2959019c12ed1a242879_CLONE/LOCAL_STREET/scaled_1000008667_1769845135030.jpg
8789                                                          https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/dace4139-b0bf-46be-bd54-0abef1feb4c9/2c94211a9a4a2a77019c12ef90db2a90_CLONE/LIVING_ROOM/scaled_1000026166_1769844694547.jpg

             Web
6451  Onehousing
6452  Onehousing
6453  Onehousing
6454  Onehousing
6455  Onehousing
...          ...
8785  Onehousing
8786  Onehousing
8787  Onehousing
8788  Onehousing
8789  Onehousing

[982 rows x 32 columns]>

In [22]:
cleaned["Lợi thế kinh doanh"].isnull().sum()

np.int64(982)

In [15]:
duplicate = cleaned[cleaned.duplicated()]
duplicate

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,Giá ước tính,Loại đơn giá (đ/m2 hoặc đ/m ngang),Đơn giá đất,Lợi thế kinh doanh,Số tầng công trình,Tổng diện tích sàn,Đơn giá xây dựng,Năm xây dựng,Chất lượng còn lại,Diện tích đất (m2),Kích thước mặt tiền (m),Kích thước chiều dài (m),Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
8776,Thành phố Hà Nội,Quận Hoàng Mai,Phường Định Công,Đường Kim Giang,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Duong-Kim-Giang-50m--P--Dinh-Cong--Q--Hoang-Mai--TP--Ha-Noi.EER1UI,Đang giao dịch,20/01/2026,None,1.700000e+10,16660000000,đ/m2,NaN,None,0.0,0.0,NaN,None,NaN,60.0,5.28,11.36,1,Chữ nhật,2.0,50.0,Đất ở,None,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a31d0d5d-38f7-4b04-9c18-7160b3bb7f33/2c9427839a4a2959019c1257e47b27fb_CLONE/LOCAL_STREET/image_picker_8713B7E0-8A27-4912-B9E3-688C2BB09D9B-22978-00001401B4E05C15_1769834762692.jpg,Onehousing
8777,Thành phố Hà Nội,Quận Long Biên,Phường Việt Hưng,Nguyễn Khắc Viện,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Nguyen-Khac-Vien-30m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.V16REK,Đang giao dịch,20/01/2026,None,2.450000e+10,24010000000,đ/m2,NaN,None,0.0,0.0,NaN,None,NaN,90.0,4.90,18.37,1,Chữ nhật,8.0,30.0,Đất ở,None,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/925f175a-7386-4ac2-9dbb-1d6c0a536a2d/2c94211a9a4a2a77019c19d9b3f62b5f_CLONE/LOCAL_STREET/scaled_1000026026_1769960807397.jpg,Onehousing
8781,Thành phố Hà Nội,Quận Long Biên,Phường Việt Hưng,Nguyễn Khắc Viện,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Nguyen-Khac-Vien-30m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.V16REK,Đang giao dịch,20/01/2026,None,2.450000e+10,24010000000,đ/m2,NaN,None,0.0,0.0,NaN,None,NaN,90.0,4.90,18.37,1,Chữ nhật,8.0,30.0,Đất ở,None,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/925f175a-7386-4ac2-9dbb-1d6c0a536a2d/2c94211a9a4a2a77019c19d9b3f62b5f_CLONE/LOCAL_STREET/scaled_1000026026_1769960807397.jpg,Onehousing
8783,Thành phố Hà Nội,Quận Hoàng Mai,Phường Định Công,Đường Kim Giang,Mặt ngõ,https://onehousing.vn/bds/Dat-nen-cach-Duong-Kim-Giang-50m--P--Dinh-Cong--Q--Hoang-Mai--TP--Ha-Noi.EER1UI,Đang giao dịch,20/01/2026,None,1.700000e+10,16660000000,đ/m2,NaN,None,0.0,0.0,NaN,None,NaN,60.0,5.28,11.36,1,Chữ nhật,2.0,50.0,Đất ở,None,21.00101,105.866667,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a31d0d5d-38f7-4b04-9c18-7160b3bb7f33/2c9427839a4a2959019c1257e47b27fb_CLONE/LOCAL_STREET/image_picker_8713B7E0-8A27-4912-B9E3-688C2BB09D9B-22978-00001401B4E05C15_1769834762692.jpg,Onehousing

In [3]:
cleaned['Thời điểm giao dịch/rao bán'] = pd.to_datetime(cleaned['Thời điểm giao dịch/rao bán'], dayfirst=True)

In [7]:
newly_scraped = cleaned[cleaned['Thời điểm giao dịch/rao bán'] >= datetime.datetime(2026, 1, 22)]
newly_scraped['Web'].value_counts()

Web
Batdongsan    2069
Name: count, dtype: int64

In [ ]:
newly_scraped.head(1)

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,Giá ước tính,Loại đơn giá (đ/m2 hoặc đ/m ngang),Đơn giá đất,Lợi thế kinh doanh,Số tầng công trình,Tổng diện tích sàn,Đơn giá xây dựng,Năm xây dựng,Chất lượng còn lại,Diện tích đất (m2),Kích thước mặt tiền (m),Kích thước chiều dài (m),Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
7340,Tỉnh Thanh Hóa,Thành phố Thanh Hóa,Phường Đông Hương,Đường Trịnh Thị Ngọc Lữ,Mặt phố,https://batdongsan.com.vn/ban-nha-rieng-duong-trinh-thi-ngoc-lu-phuong-dong-huong/ban-doi-dien-cho-thanh-hoa-pr45099908,Đang rao bán,2026-01-26,None,7.500000e+09,7350000000,đ/m2,78857613.76,Khá,4.0,284.0,8221171.0,None,0.75,71.0,4.0,17.75,1,Chữ nhật,9.5,0.0,Đất ở,"Hướng Bắc\nNhà 4 tầng kiên cố\nDiện tích: 71m² | Mặt tiền: 4m\nChỉ 50m là ra trục lớn đường đại lộ Lê Lợi\nĐường thông, ô tô đỗ cửa\nSổ hồng chính chủ\nCông năng đầy đủ: 4 phòng ngủ, 3 vệ sinh, Phòng thờ riêng, Sân phơi thoáng\nPhù hợp kinh doanh, mở văn phòng, spa, cửa hàng, cho thuê dòng tiền ổn định",19.806039,105.783255,"[""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161439-b90b_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-97fa_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161439-07d1_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-c58f_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-4c39_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-a862_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-c2ce_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/26/20260126161440-fd95_wm.jpg""]",Batdongsan

In [30]:
from seleniumbase import SB

with SB(uc=True, headed=True) as sb:
    sb.open("https://batdongsan.com.vn")

    # Click the "Đăng nhập" button
    sb.wait_for_element_visible("#kct_login", timeout=10)
    sb.click("#kct_login")

    # Wait for the login iframe to appear
    sb.wait_for_element_visible(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]',
        timeout=10
    )

    # Switch into the iframe
    sb.switch_to_frame(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]'
    )

    # Wait for the username input inside iframe
    sb.wait_for_element_visible('input[name="username"]', timeout=15)

    # Click + type (extra safe for React-based inputs)
    sb.click('input[name="username"]')
    sb.type('input[name="username"]', '0328765904')

    sb.sleep(5)