In [2]:
import pandas as pd
import sqlite3

# Test db

In [2]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [6]:
onehousing_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6836 entries, 0 to 6835
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   property_id           6833 non-null   object
 1   property_url          6836 non-null   object
 2   listing_title         6834 non-null   object
 3   total_price           6832 non-null   object
 4   unit_price            6832 non-null   object
 5   city                  6803 non-null   object
 6   district              6803 non-null   object
 7   alley_width           4785 non-null   object
 8   features              6834 non-null   object
 9   latitude              6834 non-null   float64
 10  longitude             6834 non-null   float64
 11  property_description  4896 non-null   object
 12  image_url             6834 non-null   object
dtypes: float64(2), object(11)
memory usage: 694.4+ KB

In [11]:
dup_id = onehousing_raw[onehousing_raw.duplicated()]['property_id'].unique().tolist()
len(dup_id)

786

In [26]:
onehousing_raw[(onehousing_raw['alley_width'].str.contains('\r\n')) & (onehousing_raw['alley_width'].notna())]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
0,ULHEKO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Lua-100m--P--Van-Phuc--Q--Ha-Dong--TP--Ha-Noi.ULHEKO,"Nhà mặt ngõ cách Phố Lụa 100m, P. Vạn Phúc, Q. Hà Đông, TP. Hà Nội",9.2 tỷ,271 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Bắc - 7.8m; Số tầng: 5; Diện tích: 33.9 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/355c72a5-37b5-4b62-819a-f1f34e64d071/2c9427839a4a2959019b2c413fa75633_CLONE/LIVING_ROOM/scaled_1000040570_1765975397648.jpg
1,SKUOOI,https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI,"Nhà mặt ngõ cách Xuân Đỉnh 50m, P. Xuân Đỉnh, Q. Bắc Từ Liêm, TP. Hà Nội",17 tỷ,422 triệu/m²,TP. Hà Nội,Q. Bắc Từ Liêm,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 4.1m; Số tầng: 6; Diện tích: 40.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/eb81035f-a264-4aed-932c-e524bac4e5e5/2c9427839a4a2959019ba140fe0c7de0_CLONE/LIVING_ROOM/image_picker_0225B86C-1140-496C-9131-6DC827356E26-75883-00001587015572D0_1767937910623.jpg
2,YWGUVT,https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Nguu-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.YWGUVT,"Nhà mặt ngõ cách Kim Ngưu 100m, P. Vĩnh Tuy, Q. Hai Bà Trưng, TP. Hà Nội",5.2 tỷ,203 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông Bắc - 1.2m; Số tầng: 4.5; Diện tích: 25.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/62ea34f7-62ce-4f11-92c8-cd8d8c9ca823/2c9427839a4a2959019b30c1bfac58c6_CLONE/LIVING_ROOM/scaled_1000060304_1766050118802.jpg
3,IIWMDZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ha-Tri-20m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.IIWMDZ,"Nhà mặt ngõ cách Hà Trì 20m, P. Hà Cầu, Q. Hà Đông, TP. Hà Nội",18.5 tỷ,242 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n6m - 7m,Hướng mặt tiền: Đông Nam - 5m; Số tầng: 4; Diện tích: 76.5 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8ebf97a2-39ac-491a-a797-aad2e820c127/2c9427839a4a2959019b48e5eb8d5f0c_CLONE/LIVING_ROOM/scaled_1000060911_1766455083168.jpg
4,NKHHRZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ,"Nhà mặt ngõ cách Thái Thịnh 30m, P. Thịnh Quang, Q. Đống Đa, TP. Hà Nội",19.5 tỷ,548 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\r\n3m - 4m,Hướng mặt tiền: Tây Bắc - 3.4m; Số tầng: 6; Diện tích: 35.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8995d755-c3d8-4b33-9b79-39c28c273d4f/2c9427839a4a2959019ba138a6847ddd_CLONE/LIVING_ROOM/image_picker_2E3A0736-3D43-4694-BD18-B10DAE346EF8-88338-00002DF9C82EA189_1767937353914.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,3ZDU0Y,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-Tung-Mau-200m--P--Cau-Dien--Q--Nam-Tu-Liem--TP--Ha-Noi.3ZDU0Y,"Nhà mặt ngõ cách Hồ Tùng Mậu 200m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội",8.1 tỷ,297 triệu/m²,TP. Hà Nội,Q. Nam Từ Liêm,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông - 3.9m; Số tầng: 5; Diện tích: 27.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/392d4278-2b7f-4422-868e-460288d0cc01/2c9427839a4a2959019b468985485ecf_CLONE/LIVING_ROOM/image_picker_1F0F8637-7D87-4131-AA22-CB9A4AAEEFF8-34865-000032F5B703AE4E_1766415874117.jpg
865,ANGLOU,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-De-20m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.ANGLOU,"Nhà mặt ngõ cách Bồ Đề 20m, P. Bồ Đề, Q. Long Biên, TP. Hà Nội",17.5 tỷ,328 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 3.7m; Số tầng: 7; Diện tích: 53.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/5dd47b58-65a3-41b4-ae70-bb30af8336f0/2c9427839a4a2959019b5e0f1fa269f4_CLONE/LIVING_ROOM/image_picker_2274BDFD-6944-4A03-A625-7CB0DF90408D-3465-0000025567CBBDFF_1767354176901.jpg
866,ECZA1C,https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Ha-Huy-Tap-300m--TT--Yen-Vien--H--Gia-Lam--TP--Ha-Noi.ECZA1C,"Nhà mặt ngõ cách Đường Hà Huy Tập 300m, TT. Yên Viên, H. Gia Lâm, TP. Hà Nội",3.65 tỷ,85 triệu/m²,TP. Hà Nội,H. Gia Lâm,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Tây Nam - 1.5m; Số tầng: 2; Diện tích: 43 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a4ef60e3-0b6e-4438-b5dd-96730277e20e/2c9427839a4a2959019b450a6ca25dad_CLONE/LOCAL_STREET/scaled_2081_1766390273009.jpg
867,URT8I8,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--200m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.URT8I8,"Nhà mặt ngõ cách Ngọc Thụy (mặt đê và đường gom chân đê) 200m, P. Ngọc Thụy, Q. Long Biên, TP. Hà Nội",8.6 tỷ,246 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Tây Nam - 3.7m; Số tầng: 5; Diện tích: 35 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/c578cf8f-09da-49a6-b3c9-ab5932b21dfa/2c94211a9a4a2a77019b460daaab6121_CLONE/LOCAL_STREET/scaled_IMG20251222164655_1766407188487.jpg
868,OCQGNV,https://onehousing.vn/bds/Nha-mat-pho-Dam-Quang-Trung--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.OCQGNV,"Nhà mặt phố Đàm Quang Trung, P. Long Biên, Q. Long Biên, TP. Hà Nội",12.9 tỷ,120 triệu/m²,TP. Hà Nội,Q. Long Biên,Độ rộng ngõ\r\n10m - 20m,Hướng mặt tiền: Bắc - 5m; Số tầng: 18; Số tầng hầm: 1; Diện tích: 107.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a4268e28-1629-41b0-b4da-8b7c170dd41f/2c94211a9a4a2a77019b2b6af93556bc_CLONE/LIVING_ROOM/scaled_1000073412_1766139321801.jpg

In [24]:
onehousing_raw[onehousing_raw['listing_title'].isna()]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
4432,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None

In [23]:
pd.set_option('display.max_colwidth', None)
yo = onehousing_raw[onehousing_raw['property_id'] == dup_id[0]]
yo['listing_title'].tolist()

['Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội',
 'Nhà mặt ngõ cách Quan Nhân 5m, P. Nhân Chính, Q. Thanh Xuân, TP. Hà Nội']

## Test db mới tạo

In [3]:
with sqlite3.connect('output/real_estate_test.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)

In [4]:
onehousing_raw.duplicated().sum()

np.int64(0)

In [6]:
with sqlite3.connect('output/real_estate.db') as conn:
    old_bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    old_onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [7]:
cleaned.duplicated().sum()

np.int64(248)

In [14]:
(old_onehousing_raw.shape[0] - old_onehousing_raw.duplicated(keep=False).sum()) == onehousing_raw.shape[0]
print(f'old_onehousing_raw shape: {old_onehousing_raw.shape[0]}')
print(f'onehousing_raw shape: {onehousing_raw.shape[0]}')
print(f'Num of duplicated rows: {old_onehousing_raw.duplicated(keep=False).sum()}')

old_onehousing_raw shape: 6836
onehousing_raw shape: 4494
Num of duplicated rows: 2257

# Xuất file chạy lại

In [1]:
import pandas as pd
import sqlite3
from commons.config import *
from main import clean_test

In [3]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)

bds_raw.to_csv(DETAILS_CSV_PATH['Batdongsan'], encoding='utf-8-sig', index=False)
onehousing_raw.to_csv(DETAILS_CSV_PATH['Onehousing'], encoding='utf-8-sig', index=False)

In [2]:
clean_test()

Creating database tables...
Finished creating database!
Adding raw Batdongsan data to the database at 2026-02-12 15:35:10.341736...
Finished adding raw data of Batdongsan at 2026-02-12 15:35:37.268158!
Adding raw Onehousing data to the database at 2026-02-12 15:35:37.269546...
Finished adding raw data of Onehousing at 2026-02-12 15:35:37.649626!